### ISSUE TITLE
Testowanie na lokalnym hoście. 

### ISSUE THREAD

**Issue by PolishDywan** [allegro/allegro-api#10514]
Witam, jestem nowicjuszem i chciałbym zapytać czy - mogę testować swoją plikację webową połączoną z API Allegro poprzez localhost? Czy adres przekierowań może być np. http://localhost:3001/api/auth/allegro/callback? 
Czy muszę przenieść projekt np. na VPS? 
Pozdrawiam!

**Comment by PolishDywan** [comment]
Pozwolę dodać jeszcze logi: 
`Błąd uwierzytelniania: {
  error: AxiosError: Request failed with status code 429
      at settle (C:\Users\Admin\Desktop\USEME\Zajp\server\node_modules\axios\lib\core\settle.js:19:12)
      at Unzip.handleStreamEnd (C:\Users\Admin\Desktop\USEME\Zajp\server\node_modules\axios\lib\adapters\http.js:599:11)
      at Unzip.emit (node:events:536:35)
      at Unzip.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1698:12)
      at processTicksAndRejections (node:internal/process/task_queues:90:21)
      at Axios.request (C:\Users\Admin\Desktop\USEME\Zajp\server\node_modules\axios\lib\core\Axios.js:45:41)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async AllegroService.authenticate (C:\Users\Admin\Desktop\USEME\Zajp\server\src\services\allegro.service.ts:59:24)
      at async AllegroController.getToken (C:\Users\Admin\Desktop\USEME\Zajp\server\src\controllers\allegro.controller.ts:14:21) {
    code: 'ERR_BAD_REQUEST',
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      httpsAgent: [Agent],
      method: 'post',
      url: 'https://allegro.pl.allegrosandbox.pl/auth/oauth/token',
      data: 'grant_type=client_credentials&scope=allegro%3Aapi%3Asale%3Aoffers%3Aread'
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '72',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      _header: 'POST /auth/oauth/token HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'Authorization: Basic NzA0Yzk5MzNlMDZlNDRjZGI1NmRmZGFjNzA3MGEwNzg6NHQwRUFiZVNGa0pkMDdnVWluV2ZLRUxVOWJBak5wNkFHUDgyQk9KRGtZcW16V0drSFlLVFVBRTJ0b0RwSjJRYg==\r\n' +
        'User-Agent: axios/1.7.9\r\n' +
        'Content-Length: 72\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: allegro.pl.allegrosandbox.pl\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/auth/oauth/token',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'allegro.pl.allegrosandbox.pl',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kChunkedBuffer)]: [],
      [Symbol(kChunkedLength)]: 0,
      [Symbol(kSocket)]: [TLSSocket],
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    response: {
      status: 429,
      statusText: 'Too Many Requests',
      headers: [Object [AxiosHeaders]],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    },
    status: 429
  },
  config: {
    clientId: '704c9933e06e44cdb56dfdac7070a078',
    clientSecret: '4t0EAbeSFkJd07gUinWfKELU9bAjNp6AGP82BOJDkYqmzWGkHYKTUAE2toDpJ2Qb',
    apiUrl: 'https://api.allegro.pl.allegrosandbox.pl',
    scopes: 'allegro:api:sale:offers:read'
  },
  timestamp: '2024-12-15T21:20:26.705Z'
}`

**Comment by Toumash** [comment]
> Witam, jestem nowicjuszem i chciałbym zapytać czy - mogę testować swoją plikację webową połączoną z API Allegro poprzez localhost? Czy adres przekierowań może być np. http://localhost:3001/api/auth/allegro/callback? Czy muszę przenieść projekt np. na VPS? Pozdrawiam!

Jak najbardziej, ale adres przekierowania wciąż trzeba podać podczas rejestracji aplikacji.
Błąd który dostajesz to HTTP 429 Too Many Requests czyli przekraczasz dozwoloną maksymalną liczbę zapytań.
Rekomenduję testowanie aplikacji na środowisku [Allegro sandbox](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1)
![image](https://github.com/user-attachments/assets/e4cc0973-998e-4dc1-a744-b86e4b62d1b1)


Opisane tutaj:

https://developer.allegro.pl/faq#jakie-sa-ograniczenia-liczby-sesji-i-zapytan-w-allegro-api-

> Naraz możesz mieć otwartych 20 sesji. W usłudze Allegro REST API (produkcyjnej oraz testowej) obowiązuje główny limit nakładany na Client ID (lub Sofware Statement ID w przypadku [DCR](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#dynamic-client-registration)) - 9000 zapytań na minutę.
> 
> Gdy przekroczysz limit:
> 
> na minutę zablokujemy twój Client ID,
> zwrócimy odpowiedź ze statusem: 429 Too Many Requests.
> Po tym czasie automatycznie przywrócimy dostęp do usługi dla twojego Client ID.
> 
> Dla niektórych zasobów stosujemy dodatkowe, niższe limity liczby żądań. W takich przypadkach informacje o dodatkowym limicie znajdziesz w opisie zasobu w [dokumentacji REST API Allegro](https://developer.allegro.pl/documentation).
> 
> Dla wybranych zasobów REST API stosujemy także dodatkowy mechanizm, który ogranicza liczbę zapytań dla danego użytkownika (user.id). Wykorzystujemy algorytm Leaky Bucket. Gdy użytkownik przekroczy dozwoloną liczbę wywołań na minutę (RPM), wydłużamy czas odpowiedzi. W przypadku zbyt dużej liczby równoległych zapytań w imieniu tego samego użytkownika serwer odpowie błędem HTTP: 429 Too Many Requests. Więcej - w [naszym poradniku](https://developer.allegro.pl/tutorials/b21569boAI1).
