### ISSUE TITLE
Linnworks synchronizacja stanu magazynowego

### ISSUE THREAD

**Issue by MichalSOT** [allegro/allegro-api#150]
Witam, 
nie jestem w stanie synchronizować stanu magazynowego z naszymi ofertami allegro. Za każdym razem otrzymuję następujący błąd:

Synchronize orders for AllegroPL|Step : Syncworker start Error: System.Web.Services.Protocols.SoapHeaderException: Wyszukiwana fraza nie moÅỳe zawieraÄ pewnych znakÃġw specjalnych. WiÄcej informacji na ten temat znajdziesz w dokumentacji WebAPI.
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at linnworks.syncworker.allegroInventory.allegroApi.serviceService.doGetMySellItems(String sessionId, SortOptionsStruct sortOptions, SellFilterOptionsStruct filterOptions, String searchValue, Int32 categoryId, Boolean categoryIdSpecified, Int64[] itemIds, Int32 pageSize, Boolean pageSizeSpecified, Int32 pageNumber, Boolean pageNumberSpecified, SellItemStruct[]& sellItemsList)
   at linnworks.syncworker.allegroInventory.Utility.IsLiveListing(String sessionId, String title, serviceService service)
   at linnworks.syncworker.allegroInventory.Base.SyncInventory(AllegroConfig config, String connectionString)
   at linnworks.syncworker.allegroInventory.Base.Init(Object param)

Zamówienia wpadają do systemu normalnie oraz wysztkie oferty są podpięte do produktów jednak osotatnio zauważyłem ze pomimo synchronizacji na w naszej ofercie nadal znajdował się produkt, którego nie mamy już na stanie.

**Comment by TimothyKoval** [comment]
Skontaktuj się ze swoim dostawcą oprogramowania
