### ISSUE TITLE
Problem z wygenerowaniem access_token

### ISSUE THREAD

**Issue by NoobNobody** [allegro/allegro-api#6371]
Występuje problem: 
 - [] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [x] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Witam, próbuję uzyskać token dostępowy API i napotykam się z brakiem autoryzacji.
W tym miejscu gdzie powinien pojawić się access_token serwer zwraca taką odpowiedź: 
{'error': 'Unauthorized', 'error_description': 'Unauthorized'}.
Nie wiem z czego to wynika i bardzo prosiłbym o pomoc.

Mam dosłownie taki sam kod jaki jest podany na stronie, uzupełniony o client_id oraz secret_id, lecz to nie działa: https://developer.allegro.pl/tutorials/jak-zaczac-prace-z-rest-api-4RAvV2bgwtj#php

```import requests
import json

# wprowadź Client_ID aplikacji
CLIENT_ID = "............." #uzupełnione
# wprowadź Client_Secret aplikacji
CLIENT_SECRET = ".........."  #uzupełnione
TOKEN_URL = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token"


def get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False,
                                              allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)


def main():
    access_token = get_access_token()
    print("access token = " + access_token)


if __name__ == "__main__":
    main()
 ```

W kompilerze serwer zwraca taki wynik: 
Traceback (most recent call last):
  File ".......", line 29, in <module>
    main()
  File "........", line 24, in main
    access_token = get_access_token()
  File ".......", line 17, in get_access_token
KeyError: 'access_token'

**Comment by MartaNowaczyk** [comment]
Sprawdź proszę podane Client ID, powinno być z [sandboxa](https://apps.developer.allegro.pl.allegrosandbox.pl/) nie z [produkcji](https://apps.developer.allegro.pl/).

**Comment by NoobNobody** [comment]
Dlaczego jest potrzebne Client ID z sandboxa, czy bez tego środowiska testowego nie da się wygenerować access_tokena ?

**Comment by MartaNowaczyk** [comment]
Możesz wygenerować token również dla produkcji, ale skoro wybrałeś środowisko testowe https://allegro.pl.allegrosandbox.pl/auth/oauth/token, musisz użyć danych ze środowiska testowego. 

Różnice między produkcyjnym a testowym REST API:

Produkcja:
- Adres wywołania metod - https://api.allegro.pl/
- Rejestracja aplikacji - https://apps.developer.allegro.pl/
- Adres do autoryzacji - https://allegro.pl/auth/oauth/

Sandbox:
- Adres wywołania metod - https://api.allegro.pl.allegrosandbox.pl/
- Rejestracja aplikacji - https://apps.developer.allegro.pl.allegrosandbox.pl/
- Adres do autoryzacji - https://allegro.pl.allegrosandbox.pl/auth/oauth/

**Comment by NoobNobody** [comment]
Problem w tym, że nie generowałem tokena dla środowiska testowego, tylko dla środowiska produkcyjnego

**Comment by NoobNobody** [comment]
Tak więc podane Client ID się zgadza, lecz dostaję odmowę w autoryzacji

**Comment by NoobNobody** [comment]
Gdy wchodzę w podany przez Panią link https://allegro.pl/auth/oauth/ to dostaje taki wynik, z czego wynika ten problem ?

![image](https://user-images.githubusercontent.com/83828105/202655575-c6575418-b3ca-4e39-a782-bf8c59cc4f9b.png)

**Comment by MartaNowaczyk** [comment]
W swoim kodzie masz:

> TOKEN_URL = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token"

dlatego odwołujesz się do środowiska testowego. Dla produkcji powinno być https://allegro.pl/auth/oauth/token

W poprzednim poście podałam różnice i odrębne adresy wywołań dla poszczególnych środowisk z których możesz skorzystać dla API Allegro.

**Comment by NoobNobody** [comment]
O to właśnie chodziło, bardzo dziękuję ! Takie mało przeoczenie, a tyle problemów
