### ISSUE TITLE
Błędy połączenia z API REST i częściowo SOAP

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#862]
Klienci zgłaszają nam takie błędy, zrobiłem kilka testów i coś jest na rzeczy.
Niektóre responsy z REST są puste (brak body, brak nagłówka Content-length). Niektóre requesty z SOAP po dość długim czasie wracają z kodem 500. Kilka wklejek poniżej.
```
GET https://allegroapi.io/offers/listing?phrase=OSTROVIT+WHEY+PROTEIN+2000g&searchMode=REGULAR&limit=100&sort=%2bprice&fallback=false&sellingMode.format=BUY_NOW&option=0&include=all&offset=0 HTTP/1.1
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer xxx
Api-Key: xxx
Host: allegroapi.io
Connection: Close

-----------------
HTTP/1.1 200 OK
Connection: close
X-RateLimit-Remaining: 8223
Transfer-Encoding: chunked
Trace-Id: 4e6231ac89e47aa7
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
X-RateLimit-Limit: 9000
Date: Mon, 05 Nov 2018 14:03:09 GMT
```

```
GET https://allegroapi.io/offers/listing?phrase=IHS+IRON+HORSE+IRON+TEST+90+-PILL*+-OPASKA&category.id=257689&searchMode=REGULAR&limit=100&sort=%2bprice&fallback=false&sellingMode.format=BUY_NOW&option=0&include=all&offset=0&parameter.15808=3 HTTP/1.1
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer xxxxxx
Api-Key: xxxxx
Host: allegroapi.io
Connection: Close

----------------------
HTTP/1.1 200 OK
Connection: close
X-RateLimit-Remaining: 8475
Transfer-Encoding: chunked
Trace-Id: 263fc3bd52594607
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
X-RateLimit-Limit: 9000
Date: Mon, 05 Nov 2018 14:04:06 GMT
```

```
GET https://allegroapi.io/offers/listing?phrase=ISOSTAR+KONCENTRAT+400&searchMode=REGULAR&limit=100&sort=%2bprice&fallback=false&sellingMode.format=BUY_NOW&option=0&include=all&offset=0 HTTP/1.1
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer xxxxx
Api-Key: xxxxx
Host: allegroapi.io
Connection: Close
-----------------
HTTP/1.1 200 OK
Connection: close
X-RateLimit-Remaining: 7212
Transfer-Encoding: chunked
Trace-Id: 5f9373e42161480a
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
X-RateLimit-Limit: 9000
Date: Mon, 05 Nov 2018 14:04:22 GMT
```

soap:
```
POST https://webapi.allegro.pl/service.php HTTP/1.1
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; MS Web Services Client Protocol 4.0.30319.42000)
Content-Type: text/xml; charset=utf-8
SOAPAction: "#doGetItemsInfo"
Host: webapi.allegro.pl
Content-Length: 1322
Expect: 100-continue
Connection: Close

<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><DoGetItemsInfoRequest xmlns="https://webapi.allegro.pl/service.php"><sessionHandle>xxxx</sessionHandle><itemsIdArray><item>6910172824</item><item>6910187412</item><item>6909179050</item><item>6909167608</item><item>6909167691</item><item>6909216523</item><item>6912191886</item><item>6912197237</item><item>6912223472</item><item>6912235354</item><item>6912265663</item><item>6912185681</item><item>6912190864</item><item>6913148284</item><item>6913148847</item><item>6913341397</item><item>6913356153</item><item>6913357591</item><item>6913390632</item><item>6913390693</item><item>6913390752</item><item>6913390808</item><item>6913416869</item><item>6914541180</item><item>6914554296</item></itemsIdArray><getDesc>0</getDesc><getAttribs>1</getAttribs><getPostageOptions>1</getPostageOptions><getCompanyInfo>0</getCompanyInfo><getProductInfo>0</getProductInfo><getAfterSalesServiceConditions>0</getAfterSalesServiceConditions><getEan>1</getEan><getAdditionalServicesGroup>0</getAdditionalServicesGroup></DoGetItemsInfoRequest></soap:Body></soap:Envelope>
----------------------------
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Type: text/xml;charset=UTF-8
Date: Mon, 05 Nov 2018 14:09:09 GMT

<?xml version="1.0" encoding="UTF-8" standalone="no"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Client</faultcode><faultstring xml:lang="en">Internal Server Error</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

```

**Comment by rtnet-pl** [comment]
Przy odnawianiu tokenów:
```
An error occurred while sending the request. Unable to read data from the transport connection: Connection reset by peer. [An error occurred while sending the request. [Unable to read data from the transport connection: Connection reset by peer. [Connection reset by peer]
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)]
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()]
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at TokenManager.AllegroREST.RefreshToken() in H:\C#\ktomawszystko\TokenManager\Allegro\AllegroREST.cs:line 208
   at TokenManager.Program.Main(String[] args) in H:\C#\ktomawszystko\TokenManager\Program.cs:line 26
```

**Comment by PawelTaberski** [comment]
Rzeczywiście wygląda to na jakiś problem, sprawę przekazałem do odpowiedniego zespołu. Prosiłbym o cierpliwość, sprawdzimy w czym jest problem.

**Comment by anih** [comment]
@PawelTaberski dziś za to webapi wali 404 z jsonem:

```
{"errors":[{"code":"NOT_FOUND","message":"Not Found","details":null,"path":null,"userMessage":"Not Found"}]}
```

**Comment by PawelTaberski** [comment]
@rtnet-pl Odnośnie błędów:
1/ REST API -- offers/listing - sprawdziliśmy i nie byliśmy w stanie powtórzyć problemów w logach też nic niepokojącego nie ma. Upewnij się proszę, czy problem nie występuje u Ciebie.
2/ doGetItemsInfo - obecnie mamy pewne problemy z tą metodą, pracujemy nad poprawą jej stabilności. Obecnie mogę Tobie zalecić tylko wysyłanie zapytań o mniejsze paczki.
Problem z odnawianiem tokenów jeszcze badamy proszę o cierpliwość.
@anih Przy jakiej metodzie dostałeś taki respons?

**Comment by anih** [comment]
@PawelTaberski na szybko z tracebacków to doGetSiteJournal, doGetSellFormFieldsForCategory, doGetSiteJournalDeals

**Comment by anih** [comment]
ale za którymś ponowieniem przechodzi, więc możliwe, że część serwerów obsługujących webapi jest dotknięta problemem

**Comment by PawelTaberski** [comment]
Rzeczywiście są jakieś problemy, sprawę już przekazałem do odpowiedniego zespołu. Proszę o cierpliwość.

**Comment by PawelTaberski** [comment]
@anih Problem nie powinien już występować.
