### ISSUE TITLE
Shipment size Error: 'Error: Seller didnt provide credentials for own delivery Method Wybrana metoda dostawy nie obsługuje tego zamówienia'

### ISSUE THREAD

**Issue by kamilkomtek** [allegro/allegro-api#9154]
Witam
Mój integrator odesłał mnie do allegro Shipment size Error: 'Error: Seller didnt provide credentials for own delivery Method Wybrana metoda dostawy nie obsługuje tego zamówienia' 

lub 
Błąd:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo/models.py", line 5096, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/addons/web/controllers/main.py", line 1331, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/ideaerp_addons/ideaerp_base/models/ideaerp_snippets.py", line 114, in wrapper
    return getattr(self.with_context(**ctx_kw), func.__name__)(*args, **kwargs)
  File "/odoo/ideaerp_addons/ideaerp_base/models/ideaerp_snippets.py", line 113, in wrapper
    return func(self.with_context(**ctx_kw), *args, **kwargs)
  File "/odoo/ideaerp_addons/ideaerp_base/models/shipping_order.py", line 513, in generate_waybill
    data = self.prepare_shipment_data()
  File "/odoo/ideaerp_addons/ideaerp_shipment_poczta_polska/models/shipping_order.py", line 49, in prepare_shipment_data
    res = super(ShippingOrder, self).prepare_shipment_data()
  File "/odoo/ideaerp_addons/ideaerp_shipment_jas_fbg/models/shipping_order.py", line 41, in prepare_shipment_data
    res = super(ShippingOrder, self).prepare_shipment_data()
  File "/odoo/ideaerp_addons/ideaerp_shipment_furgonetka/models/shipping_order.py", line 121, in prepare_shipment_data
    res = super(ShippingOrder, self).prepare_shipment_data()
  File "/odoo/ideaerp_addons/ideaerp_shipment_dhl/models/shipping_order.py", line 38, in prepare_shipment_data
    res = super(ShippingOrder, self).prepare_shipment_data()
  File "/odoo/ideaerp_addons/ideaerp_base/models/shipping_order.py", line 370, in prepare_shipment_data
    data.update(self.get_services_data())
  File "/odoo/ideaerp_addons/ideaerp_shipment_wza/models/shipping_order.py", line 118, in get_services_data
    data['services']['service'] = allegro_map.allegro_carrier_id
  File "/odoo/odoo/fields.py", line 988, in __get__
    record.ensure_one()
  File "/odoo/odoo/models.py", line 5099, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: allegro.account.carrier.map(237, 488)

Proszę o pomoc bo nie mogę nadać paczek. Błąd występuje tylko przy metodzie dostawy

Kamil

Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by MartaNowaczyk** [comment]
Witam, 
dane, które przesłałeś nie są przydatne do weryfikacji po stronie allegro. Do weryfikacji integrator powinien podać trace-id, albo podać inne dane jak command-id.  
Po treści błędu mogę wywnioskować, że wygląda to na próbę wykorzystania metody dostawy, która wymaga umowy własnej z przewoźnikiem, a którą powinieneś spróbować dodać w ustawieniach WzA:
[https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1#j[…]ro](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1#jak-dodac-umowe-wlasna-w-wysylam-z-allegro) lub inna możliwość, to podczas tworzenia przesyłki nie była przekazana umowa własna/była przekazana błędnie. Bez danych, które pozwolą mi spojrzeć w logi tylko tyle mogę wskazać.

**Comment by kamilkomtek** [comment]
Integrator odmówił mi podania logów. Czy mogę prosić o przesłanie wszystkich logów dla mojego konta.

**Comment by MartaNowaczyk** [comment]
Niestety, nie mam takiej możliwości by przesłać wszystkie logi.
